updated increase timeout for k8s job

diff --git a/.github/workflows/kubernetes.yaml b/.github/workflows/kubernetes.yaml
--- a/.github/workflows/kubernetes.yaml
+++ b/.github/workflows/kubernetes.yaml
@@ -35,8 +35,16 @@ jobs:
 
       - name: Wait for Test Execution
         run: |
-          kubectl wait --for=condition=complete job/playwright-test-job --timeout=180s || \
-          kubectl wait --for=condition=failed job/playwright-test-job --timeout=10s
+          kubectl wait --for=condition=complete job/playwright-test-job --timeout=600s || {
+            echo "--- POD STATUS ---"
+            kubectl get pods
+            echo "--- JOB DESCRIPTION ---"
+            kubectl describe job playwright-test-job
+            echo "--- CONTAINER LOGS ---"
+            kubectl logs -l job-name=playwright-test-job
+            exit 1
+          }
+        # kubectl wait --for=condition=failed job/playwright-test-job --timeout=10s
 
       - name: Retrieve Allure Reports
         if: always()
